import type { OracleCard, CardListItem } from '../types/card'

export const mockBolt: OracleCard = {
  oracle_id: '4457ed35-7c10-48c8-9776-456485fdf070',
  name: 'Lightning Bolt',
  mana_cost: '{R}',
  cmc: 1,
  type_line: 'Instant',
  oracle_text: 'Lightning Bolt deals 3 damage to any target.',
  power: null,
  toughness: null,
  loyalty: null,
  hand_modifier: null,
  life_modifier: null,
  colors: ['R'],
  color_identity: ['R'],
  produced_mana: [],
  keywords: [],
  legalities: {
    standard: 'not_legal',
    pioneer: 'not_legal',
    modern: 'legal',
    legacy: 'legal',
    vintage: 'legal',
    commander: 'legal',
    pauper: 'legal',
    explorer: 'not_legal',
    historic: 'not_legal',
    timeless: 'legal',
  } as OracleCard['legalities'],
  layout: 'normal',
  reserved: false,
  games: ['paper', 'mtgo'],
  card_faces: null,
  canonical_scryfall_id: 'f29ba16f-c8fb-42fe-aabf-87089cb214a7',
  rulings: [],
  image_urls: {
    normal: 'https://example.com/bolt-normal.jpg',
    art_crop: 'https://example.com/bolt-art.jpg',
  },
}

export const mockGoyf: OracleCard = {
  oracle_id: '45900b2f-f6a9-4c42-9642-008f3c1cf6dd',
  name: 'Tarmogoyf',
  mana_cost: '{1}{G}',
  cmc: 2,
  type_line: 'Creature — Lhurgoyf',
  oracle_text: "Tarmogoyf's power is equal to the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.",
  power: '*',
  toughness: '1+*',
  loyalty: null,
  hand_modifier: null,
  life_modifier: null,
  colors: ['G'],
  color_identity: ['G'],
  produced_mana: [],
  keywords: [],
  legalities: {
    standard: 'not_legal',
    pioneer: 'not_legal',
    modern: 'legal',
    legacy: 'legal',
    vintage: 'legal',
    commander: 'legal',
    pauper: 'not_legal',
    explorer: 'not_legal',
    historic: 'legal',
    timeless: 'legal',
  } as OracleCard['legalities'],
  layout: 'normal',
  reserved: false,
  games: ['paper', 'mtgo', 'arena'],
  card_faces: null,
  canonical_scryfall_id: '73d1e820-3714-4800-a220-5e4d5cfbfb7e',
  rulings: [],
  image_urls: {
    normal: 'https://example.com/goyf-normal.jpg',
    art_crop: 'https://example.com/goyf-art.jpg',
  },
}

export const mockJace: OracleCard = {
  oracle_id: 'aaa-bbb-ccc',
  name: 'Jace, the Mind Sculptor',
  mana_cost: '{2}{U}{U}',
  cmc: 4,
  type_line: 'Legendary Planeswalker — Jace',
  oracle_text: '+2: Look at the top card of target player\'s library.\n0: Draw three cards, then put two cards from your hand on top of your library.\n-1: Return target creature to its owner\'s hand.\n-12: Exile all cards from target player\'s library, then that player shuffles their hand into their library.',
  power: null,
  toughness: null,
  loyalty: '3',
  hand_modifier: null,
  life_modifier: null,
  colors: ['U'],
  color_identity: ['U'],
  produced_mana: [],
  keywords: [],
  legalities: {
    standard: 'not_legal',
    pioneer: 'not_legal',
    modern: 'legal',
    legacy: 'legal',
    vintage: 'restricted',
    commander: 'legal',
    pauper: 'not_legal',
    explorer: 'not_legal',
    historic: 'not_legal',
    timeless: 'legal',
  } as OracleCard['legalities'],
  layout: 'normal',
  reserved: false,
  games: ['paper', 'mtgo'],
  card_faces: null,
  canonical_scryfall_id: 'ddd-eee-fff',
  rulings: [],
  image_urls: {
    normal: 'https://example.com/jace-normal.jpg',
  },
}

export const mockBoltListItem: CardListItem = {
  oracle_id: mockBolt.oracle_id,
  name: 'Lightning Bolt',
  mana_cost: '{R}',
  cmc: 1,
  type_line: 'Instant',
  colors: ['R'],
  color_identity: ['R'],
  keywords: [],
  legal_formats: ['modern', 'legacy', 'vintage', 'commander', 'pauper', 'timeless'],
  layout: 'normal',
  art_crop: 'https://example.com/bolt-art.jpg',
}

export const mockGoyfListItem: CardListItem = {
  oracle_id: mockGoyf.oracle_id,
  name: 'Tarmogoyf',
  mana_cost: '{1}{G}',
  cmc: 2,
  type_line: 'Creature — Lhurgoyf',
  colors: ['G'],
  color_identity: ['G'],
  keywords: [],
  legal_formats: ['modern', 'legacy', 'vintage', 'commander', 'historic', 'timeless'],
  layout: 'normal',
  art_crop: 'https://example.com/goyf-art.jpg',
}
